In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [22]:
!pip install tensorflow

In [4]:
### sentences
sent = [
    'The quick brown fox jumps over the lazy dog',
    'The quick brown fox jumps over the lazy dog again',
    'the cup of tea'
    'The cup of tea is hot',
    'I am a good developer',
    'I am a good developer and I am a good person',

]

In [5]:
sent

['The quick brown fox jumps over the lazy dog',
 'The quick brown fox jumps over the lazy dog again',
 'the cup of teaThe cup of tea is hot',
 'I am a good developer',
 'I am a good developer and I am a good person']

In [6]:
## define vocabulary size
vocab_size = 10000

In [7]:
## one hot representation
one_hot_repr = [one_hot(words,vocab_size)for words in sent]
print(one_hot_repr)

[[3212, 645, 1598, 8637, 6192, 705, 3212, 3289, 6628], [3212, 645, 1598, 8637, 6192, 705, 3212, 3289, 6628, 2508], [3212, 1854, 2203, 8006, 1854, 2203, 1502, 1405, 2605], [4088, 5417, 6139, 1775, 4668], [4088, 5417, 6139, 1775, 4668, 9895, 4088, 5417, 6139, 1775, 2492]]


In [ ]:
## word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [10]:
sent_length = 12
embedded_docs = pad_sequences(one_hot_repr,padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0 3212  645 1598 8637 6192  705 3212 3289 6628]
 [   0    0 3212  645 1598 8637 6192  705 3212 3289 6628 2508]
 [   0    0    0 3212 1854 2203 8006 1854 2203 1502 1405 2605]
 [   0    0    0    0    0    0    0 4088 5417 6139 1775 4668]
 [   0 4088 5417 6139 1775 4668 9895 4088 5417 6139 1775 2492]]


In [24]:
## feature representation
dim = 12
model = Sequential()
model.add(Embedding(vocab_size, dim, input_length = sent_length))
model.compile('adam','mse')


In [25]:
# Build the model by passing input data
model.build(input_shape=(None, sent_length))

# Print the model summary
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 12, 12)         │       120,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 120,000 (468.75 KB)

 Trainable params: 120,000 (468.75 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 12, 12)         │       120,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 120,000 (468.75 KB)

 Trainable params: 120,000 (468.75 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 495ms/step


array([[[-6.2545761e-03,  4.8852634e-02, -2.4784327e-02,  2.7212929e-02,
         -4.3420684e-02,  6.6311955e-03, -5.7796612e-03,  1.3052598e-03,
         -3.7974190e-02, -2.4471868e-02,  5.2367449e-03,  1.6301695e-02],
        [-6.2545761e-03,  4.8852634e-02, -2.4784327e-02,  2.7212929e-02,
         -4.3420684e-02,  6.6311955e-03, -5.7796612e-03,  1.3052598e-03,
         -3.7974190e-02, -2.4471868e-02,  5.2367449e-03,  1.6301695e-02],
        [-6.2545761e-03,  4.8852634e-02, -2.4784327e-02,  2.7212929e-02,
         -4.3420684e-02,  6.6311955e-03, -5.7796612e-03,  1.3052598e-03,
         -3.7974190e-02, -2.4471868e-02,  5.2367449e-03,  1.6301695e-02],
        [ 3.9082740e-02,  3.3581976e-02,  2.8862145e-02, -1.5569508e-02,
          2.7238097e-02, -9.3583241e-03, -2.7926851e-02,  1.7526831e-02,
         -3.2274142e-02,  3.5632420e-02, -2.1595443e-02,  4.5294467e-02],
        [-6.5803640e-03,  1.8651757e-02, -9.1457590e-03,  6.5107569e-03,
          4.1061308e-02,  1.2301732e-02, -1.986